# API Configuration
api:
  base-path: /api/v1

spring:
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/biding
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

# Logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      jooq: DEBUG
